"""
Regenerate publication figures for the manuscript.

Currently supports:
    --figure r2                Figure 16 (mass-robustness scatter: angular + position
                               error). Note: post-renumbering — was Figure 17.
    --figure sine              Figure 21 (sinusoidal fit to box motion under
                               deterministic circular pushing; left and right
                               circle panels). Note: post-renumbering.
    --figure straight_gallery  Figure 17 panel (a): zoomed timestamped 2x4 gallery
                               extracted from 03_Straight_Line_Box_Pushing.mp4.
                               Per-frame yellow-blob centroid tracking keeps the
                               robot centred across the eight panels.
    --figure bezier_panelb     Figure 17 panel (b): close-up 2x4 timestamped
                               gallery extracted from 02_Bezier_Trajectory_Box_
                               Pushing.mp4, showing one leg pushing the box with
                               the green Bezier-curve trajectory visible.
    --figure all               r2 + sine (the data-driven figures). The video
                               gallery modes are opt-in via the explicit names
                               above to avoid overwriting curated PNGs.

Note: Figure 18b (straight-line box-corner XY trajectory) is sourced from the
canonical MATLAB-side log that lives outside this repository; the on-disk
file figures/Box_Trajectory_Straight.png is treated as authoritative and is
not regenerated by this script. The CSV under supplementary/data/Cube.csv
captures corner trajectories from a separate rollout and does not include
target positions, so a re-render here would not match the published plot.

For Figure 16, the source data are the (delta_mass_percent, error) pairs
extracted from R_squerd_Theta.fig and R_squerd_Position.fig and are inlined
in this file as DM_PCT / ANGULAR_ERR_DEG / POSITION_ERR_M.

For Figure 21, the source data are downsampled measured box-coordinate
trajectories together with the recomputed sinusoidal-fit parameters. These
were extracted from Sin_Curve_L.fig / Sin_Curve_R.fig and stored as
../../data/sine_wave/sine_curve_l.npz and sine_curve_r.npz. Each .npz
contains x, y, A, omega, phi, c, rmse, r2, period, t_fit_start, t_fit_end.

For Figure 17 panels (a) and (b), the source media live alongside this
script at ../../videos/ as the renamed MDPI supplementary clips.

Outputs:
    figures/R_squared_Angle.png        (Fig. 16a)
    figures/R_squared_Position.png     (Fig. 16b)
    figures/Sine_Waves.png             (Fig. 21, two-panel composite)
    figures/Straight_Push_Gallery.png  (Fig. 17a, 2x4 zoomed timestamped)
    figures/Robodog_Push.png           (Fig. 17b, 2x4 close-up timestamped)
"""
import argparse
import io
import subprocess
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageDraw, ImageFont


# =============================================================================
# Figure 17 — mass-robustness scatter
# =============================================================================
# Source data extracted from R_squerd_Theta.fig and R_squerd_Position.fig
DM_PCT = np.array([0, 200, 300, 400, 500, 600, 700, 800])
TRAINING_MASS_KG = 0.1

ANGULAR_ERR_DEG = np.array([
    0.5911537933778277, 0.3768327933348701, 1.3430550471189093,
    1.9442670676834553, 2.158606090235409, 2.9939035342999745,
    5.26384766367498, 6.317648200427115,
])

POSITION_ERR_M = np.array([
    0.180735877161401, 0.217125456208026, 0.27788678842291237,
    0.29815871588513, 0.418478022222738, 0.521990905509768,
    0.6193407376977563, 0.63964983593706,
])

MARKER_FACE = "#1f4e79"
MARKER_EDGE = "#0b1f33"
FIT_LINE = "#333333"


def linear_fit_nonneg(x, y):
    """Descriptive linear trend with intercept constrained to be >= 0.
    Returns (slope, intercept, r2). Avoids implying nonphysical negative
    error at low mass, since OLS on a few points can produce a negative
    intercept that has no physical meaning for an error metric.
    """
    slope_ols, intercept_ols = np.polyfit(x, y, 1)
    if intercept_ols >= 0:
        slope, intercept = slope_ols, intercept_ols
    else:
        # Refit with intercept fixed at 0: y = s*x; s = (x.y) / (x.x)
        slope = float(np.dot(x, y) / np.dot(x, x))
        intercept = 0.0
    y_hat = slope * x + intercept
    ss_res = np.sum((y - y_hat) ** 2)
    ss_tot = np.sum((y - y.mean()) ** 2)
    r2 = 1.0 - ss_res / ss_tot
    return slope, intercept, r2


def r2_panel(ax, x, y, ylabel, unit_label, slope_unit_short):
    slope, intercept, r2 = linear_fit_nonneg(x, y)
    x_fit = np.linspace(x.min(), x.max(), 200)
    y_fit = slope * x_fit + intercept

    ax.plot(x_fit, y_fit, linestyle="--", linewidth=1.6, color=FIT_LINE, zorder=2)
    ax.scatter(x, y, s=70, facecolor=MARKER_FACE, edgecolor=MARKER_EDGE,
               linewidths=0.7, zorder=3)

    ax.set_xlim(-50, 850)
    ax.set_ylim(0, max(y.max() * 1.12, 1e-3))
    ax.set_xticks([0, 200, 400, 600, 800])
    ax.set_xlabel(r"Relative mass increase, $\Delta m / m_{\mathrm{train}}$ (%)", fontsize=10)
    ax.set_ylabel(ylabel + f" ({unit_label})", fontsize=10)
    ax.tick_params(axis="both", labelsize=9)
    ax.grid(True, axis="y", linestyle="-", color="#dddddd", linewidth=0.5, alpha=0.9)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    ax.spines["left"].set_linewidth(0.8)
    ax.spines["bottom"].set_linewidth(0.8)

    # Slope per 100% mass increase; compact, unboxed, in bottom-right
    slope_per_100 = slope * 100.0
    note = (f"slope: {slope_per_100:.2f} {slope_unit_short} per 100% mass increase\n"
            f"$R^2$: {r2:.2f}  (descriptive linear trend)")
    ax.text(0.97, 0.04, note, transform=ax.transAxes, fontsize=8.5,
            ha="right", va="bottom", family="serif", color="#222222")


def render_r2(outdir: Path):
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["DejaVu Serif", "Liberation Serif", "Times New Roman"],
        "mathtext.fontset": "dejavuserif",
        "axes.titlesize": 10,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
    })

    for path, x, y, ylabel, unit, slope_unit in [
        (outdir / "R_squared_Angle.png", DM_PCT, ANGULAR_ERR_DEG,
         "Angular error", r"$^{\circ}$", r"$^{\circ}$"),
        (outdir / "R_squared_Position.png", DM_PCT, POSITION_ERR_M,
         "Position error", "m", "m"),
    ]:
        fig, ax = plt.subplots(figsize=(5.2, 3.6))
        r2_panel(ax, x, y, ylabel, unit, slope_unit)
        fig.savefig(path)
        plt.close(fig)
        print(f"wrote {path}")


# =============================================================================
# Figure 22 — sinusoidal fit to box motion under deterministic circular pushing
# =============================================================================
# Colorblind-safe palette (Wong) + line-style differentiation, so the two
# series remain distinguishable in grayscale print:
#   measured signal -> solid vermillion (#D55E00)
#   fitted sinusoid -> dashed near-black (#222222)
MEASURED_COLOR = "#D55E00"
FIT_COLOR = "#222222"
TRANSIENT_SHADE = "#f2f2f2"

# Resolve a stable relative path to the bundled signal data: this script lives
# at supplementary/code/python/, and the data lives at supplementary/data/.
SINE_DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "sine_wave"


def _sine_panel(ax, npz_path, panel_title, xlim, ylim):
    d = np.load(npz_path)
    x = d["x"].astype(float)
    y = d["y"].astype(float)
    A = float(d["A"])
    omega = float(d["omega"])
    phi = float(d["phi"])
    c = float(d["c"])
    r2 = float(d["r2"])
    rmse = float(d["rmse"])
    t_fit_start = float(d["t_fit_start"])
    t_fit_end = float(d["t_fit_end"])

    # Shade the transient (pre-fit) region so reviewers can see what was
    # excluded from the parameter estimation.
    if t_fit_start > x.min():
        ax.axvspan(x.min(), t_fit_start, color=TRANSIENT_SHADE, zorder=0)
        ax.text(t_fit_start + 0.005 * (xlim[1] - xlim[0]),
                ylim[0] + 0.04 * (ylim[1] - ylim[0]),
                "transient\n(excluded)", fontsize=7.0, ha="left", va="bottom",
                color="#888888", family="serif")

    # Evaluate the fitted model on a uniform dense grid over the fit window
    t_dense = np.linspace(t_fit_start, t_fit_end, 1500)
    y_fit_dense = A * np.sin(omega * t_dense + phi) + c

    ax.plot(x, y, color=MEASURED_COLOR, linewidth=1.0, label="Measured",
            zorder=2)
    ax.plot(t_dense, y_fit_dense, color=FIT_COLOR, linestyle="--",
            linewidth=1.4, label=r"Fit: $A\sin(\omega t+\varphi)+c$",
            zorder=3)

    ax.set_xlim(*xlim)
    ax.set_ylim(*ylim)
    ax.set_xlabel(r"Time $t$ [s]", fontsize=10)
    ax.set_ylabel(r"Box coordinate $q(t)$ [sim. units]", fontsize=10)
    ax.set_title(panel_title, fontsize=10)
    ax.tick_params(axis="both", labelsize=9)
    ax.grid(True, axis="y", linestyle="-", color="#dddddd", linewidth=0.5, alpha=0.9)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    ax.spines["left"].set_linewidth(0.8)
    ax.spines["bottom"].set_linewidth(0.8)

    # Parameter annotation, compact and unboxed, upper-right (above the
    # bottom-of-axis legend; sits in negative half-cycle gaps)
    period = 2 * np.pi / omega
    note = ("\n".join([
        rf"$A={A:.2f}$,  $c={c:.2f}$",
        rf"$\omega={omega*1000:.3f}\times10^{{-3}}$ rad/s",
        rf"$T \approx {period/1000:.1f}\times10^{{3}}$ s",
        rf"$\varphi={phi:+.2f}$ rad",
        rf"$R^{{2}}={r2:.2f}$,  RMSE $={rmse:.2f}$",
    ]))
    ax.text(0.985, 0.97, note, transform=ax.transAxes, fontsize=7.8,
            ha="right", va="top", family="serif", color="#222222",
            linespacing=1.30,
            bbox=dict(boxstyle="round,pad=0.25", facecolor="white",
                      edgecolor="#cccccc", linewidth=0.5, alpha=0.92))


def render_sine(outdir: Path):
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["DejaVu Serif", "Liberation Serif", "Times New Roman"],
        "mathtext.fontset": "dejavuserif",
        "axes.titlesize": 10,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
    })

    # Determine shared axis limits across both panels for visual comparability
    l = np.load(SINE_DATA_DIR / "sine_curve_l.npz")
    r = np.load(SINE_DATA_DIR / "sine_curve_r.npz")
    x_max = float(max(l["x"].max(), r["x"].max()))
    y_min = float(min(l["y"].min(), r["y"].min()))
    y_max = float(max(l["y"].max(), r["y"].max()))
    pad = 0.05 * (y_max - y_min)
    xlim = (0.0, x_max * 1.02)
    ylim = (y_min - pad, y_max + pad)

    fig, axes = plt.subplots(1, 2, figsize=(9.6, 4.0), constrained_layout=True)
    _sine_panel(axes[0], SINE_DATA_DIR / "sine_curve_l.npz",
                "Left-circle pushing (counterclockwise)", xlim, ylim)
    _sine_panel(axes[1], SINE_DATA_DIR / "sine_curve_r.npz",
                "Right-circle pushing (clockwise)", xlim, ylim)

    # Single, shared, unboxed legend below the panels
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2,
               frameon=False, fontsize=9, bbox_to_anchor=(0.5, -0.04))

    out = outdir / "Sine_Waves.png"
    fig.savefig(out)
    plt.close(fig)
    print(f"wrote {out}")


# =============================================================================
# Figure 17 — straight-push gallery (panel a) and Bezier-trajectory close-up
# (panel b) — frame-extraction + per-frame zoom + timestamp stamping
# =============================================================================
# Videos live two levels up from this script under supplementary/videos/
VIDEOS_DIR = Path(__file__).resolve().parents[2] / "videos"

# Viewport of the straight-push video that excludes the CoppeliaSim scene-
# hierarchy panel on the left (so robot-tracking only searches inside the 3-D
# viewport, never matches yellow widgets in the panel).
STRAIGHT_VIEWPORT = (320, 0, 1280, 458)  # (x0, y0, x1, y1)

# Path to a TrueType font with consistent metrics across systems.
_FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
    "/Library/Fonts/Arial Bold.ttf",
    "C:/Windows/Fonts/arialbd.ttf",
]


def _load_font(size):
    for p in _FONT_CANDIDATES:
        if Path(p).exists():
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def _extract_frame(video_path: Path, t_seconds: float) -> Image.Image:
    """Return a single decoded frame at ``t_seconds`` as a PIL RGB image.
    Uses ffmpeg with ``-ss`` before ``-i`` for fast keyframe seek; for short
    clips this is accurate enough for the purposes of a figure gallery.
    """
    cmd = ["ffmpeg", "-y", "-ss", f"{t_seconds:.3f}", "-i", str(video_path),
           "-frames:v", "1", "-f", "image2", "-c:v", "png", "pipe:1"]
    res = subprocess.run(cmd, capture_output=True, check=True)
    return Image.open(io.BytesIO(res.stdout)).convert("RGB")


def _yellow_centroid(img: Image.Image, viewport):
    """Centroid (cx, cy) in image coordinates of bright-yellow pixels
    restricted to ``viewport`` (Spot's chassis colour). Returns None if no
    yellow pixels are found.
    """
    x0, y0, x1, y1 = viewport
    arr = np.asarray(img.crop((x0, y0, x1, y1)))
    r = arr[:, :, 0].astype(int)
    g = arr[:, :, 1].astype(int)
    b = arr[:, :, 2].astype(int)
    mask = (r > 180) & (g > 130) & (b < 110) & ((r - b) > 80)
    ys, xs = np.where(mask)
    if xs.size == 0:
        return None
    return int(xs.mean()) + x0, int(ys.mean()) + y0


def _smart_crop(img: Image.Image, cx: int, cy: int, crop_w: int, crop_h: int,
                viewport) -> Image.Image:
    """Crop ``crop_w x crop_h`` centred on (cx, cy), clamped inside ``viewport``
    so the scene-hierarchy panel never sneaks back in."""
    vx0, vy0, vx1, vy1 = viewport
    half_w, half_h = crop_w // 2, crop_h // 2
    x0 = max(vx0, min(cx - half_w, vx1 - crop_w))
    y0 = max(vy0, min(cy - half_h, vy1 - crop_h))
    return img.crop((x0, y0, x0 + crop_w, y0 + crop_h))


def _stamp_timestamp(img: Image.Image, t_seconds: float,
                     font_height_frac: float = 0.08,
                     margin_frac: float = 0.04,
                     pos: str = "bottom-left") -> None:
    """Stamp ``t = X.X s`` in a black chip with white text in ``img``.

    The font size auto-scales as a fraction of image height, and the chip is
    inset from the image edges by a fraction of the smaller dimension.  This
    makes the printed appearance consistent across panels even when the source
    panels have very different pixel resolutions (e.g. panel a at 500x350 vs
    panel b at 1280x800 -- without auto-scaling the same pixel font would
    print at very different physical sizes after the LaTeX scale-to-width).
    """
    W, H = img.size
    font_size = max(10, int(H * font_height_frac))
    margin = max(4, int(min(W, H) * margin_frac))
    font = _load_font(font_size)
    draw = ImageDraw.Draw(img)
    txt = f"t = {t_seconds:.1f} s"
    # PIL's textbbox origin is offset from the draw anchor because glyph
    # metrics include leading space (ascent gap, side bearings).  We need both
    # the visual width/height (tw, th) for sizing the chip AND the offsets
    # (bx0, by0) so we can shift the draw call and put the GLYPH -- not the
    # font's metric box -- at (x_box + pad, y_box + pad) inside the chip.
    # Without subtracting (bx0, by0) the text rides low / off-centre in the
    # black rectangle, which is what the rendered Fig 17 was showing.
    bx0, by0, bx1, by1 = draw.textbbox((0, 0), txt, font=font)
    tw, th = bx1 - bx0, by1 - by0
    pad = max(4, font_size // 5)
    if pos == "bottom-left":
        x_box, y_box = margin, H - th - 2 * pad - margin
    elif pos == "top-right":
        x_box, y_box = W - tw - 2 * pad - margin, margin
    else:
        x_box, y_box = margin, margin
    draw.rectangle((x_box, y_box, x_box + tw + 2 * pad,
                    y_box + th + 2 * pad), fill="black")
    draw.text((x_box + pad - bx0, y_box + pad - by0),
              txt, fill="white", font=font)


def _mosaic(panels, cols: int, rows: int, gap: int = 4,
            bg: str = "white") -> Image.Image:
    pw, ph = panels[0].size
    W = pw * cols + gap * (cols + 1)
    H = ph * rows + gap * (rows + 1)
    sheet = Image.new("RGB", (W, H), bg)
    for i, p in enumerate(panels):
        r, c = divmod(i, cols)
        x = gap + c * (pw + gap)
        y = gap + r * (ph + gap)
        sheet.paste(p, (x, y))
    return sheet


def render_straight_gallery(outdir: Path, src_video: Path):
    """Figure 17a: eight zoomed timestamped frames of straight-line pushing."""
    timestamps = [5.0, 18.0, 32.0, 46.0, 60.0, 74.0, 88.0, 102.0]
    crop_w, crop_h = 500, 350
    panels = []
    for t in timestamps:
        frame = _extract_frame(src_video, t)
        centroid = _yellow_centroid(frame, STRAIGHT_VIEWPORT)
        if centroid is None:
            # Fallback to viewport centre — robot temporarily out of view.
            vx0, vy0, vx1, vy1 = STRAIGHT_VIEWPORT
            centroid = ((vx0 + vx1) // 2, (vy0 + vy1) // 2)
        cropped = _smart_crop(frame, centroid[0], centroid[1],
                              crop_w, crop_h, STRAIGHT_VIEWPORT)
        _stamp_timestamp(cropped, t)
        panels.append(cropped)
    sheet = _mosaic(panels, cols=4, rows=2, gap=4)
    out = outdir / "Straight_Push_Gallery.png"
    sheet.save(out, dpi=(300, 300))
    print(f"wrote {out} ({sheet.size})")


def render_bezier_panelb(outdir: Path, src_video: Path):
    """Figure 17b: eight close-up timestamped frames of one-leg Bezier-curve
    pushing. The source video is already framed tightly on the leg + box, so
    a static centre crop suffices and no robot tracking is needed."""
    timestamps = [0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5]
    crop_w, crop_h = 1280, 800
    panels = []
    for t in timestamps:
        frame = _extract_frame(src_video, t)
        W, H = frame.size
        x0 = max(0, (W - crop_w) // 2)
        y0 = max(0, (H - crop_h) // 2)
        cropped = frame.crop((x0, y0, x0 + crop_w, y0 + crop_h))
        _stamp_timestamp(cropped, t)
        panels.append(cropped)
    sheet = _mosaic(panels, cols=4, rows=2, gap=4)
    out = outdir / "Robodog_Push.png"
    sheet.save(out, dpi=(300, 300))
    print(f"wrote {out} ({sheet.size})")


# =============================================================================
# CLI
# =============================================================================
def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--figure",
                        choices=("r2", "sine",
                                 "straight_gallery", "bezier_panelb", "all"),
                        default="all",
                        help="Which figure to regenerate. 'all' covers the "
                             "data-driven figures (r2, sine); the video "
                             "galleries are opt-in by explicit name.")
    args = parser.parse_args()

    here = Path(__file__).resolve()
    # Outputs land in <repo>/figures/, four levels up from this script
    out = here.parents[3] / "figures"
    if not out.exists():
        raise SystemExit(f"figures/ not found at {out}")

    if args.figure in ("r2", "all"):
        render_r2(out)
    if args.figure in ("sine", "all"):
        render_sine(out)
    if args.figure == "straight_gallery":
        src = VIDEOS_DIR / "03_Straight_Line_Box_Pushing.mp4"
        if not src.exists():
            raise SystemExit(f"video not found: {src}")
        render_straight_gallery(out, src)
    if args.figure == "bezier_panelb":
        src = VIDEOS_DIR / "02_Bezier_Trajectory_Box_Pushing.mp4"
        if not src.exists():
            raise SystemExit(f"video not found: {src}")
        render_bezier_panelb(out, src)


if __name__ == "__main__":
    main()
